apiVersion: v1
kind: Secret
metadata:
  name: food-decider-tg-bot-secrets
  annotations:
    avp.kubernetes.io/path: 'kv/data/tg-bots/food-decider'
stringData:
  BOT_TOKEN: <botToken>
  DB_HOST: <path:kv/data/k8s/common/mysql#host>
  DB_PASS: <path:kv/data/k8s/common/mysql#password>
  DB_USER: <path:kv/data/k8s/common/mysql#user>
  GMAPS_API_KEY: <gmapsKey>
type: Opaque
