apiVersion: v1
kind: Secret
metadata:
  name: food-decider-tg-bot-secrets
  labels:
    app.kubernetes.io/name: "food-decider-telegram-bot"
    app.kubernetes.io/instance: "food-decider-telegram-bot-live"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "secrets"
    app.kubernetes.io/part-of: "food-decider-telegram-bot"
    app.kubernetes.io/managed-by: "argo"
  annotations:
    avp.kubernetes.io/path: 'kv/data/tg-bots/food-decider'
stringData:
  BOT_TOKEN: <botToken>
  DB_HOST: <path:kv/data/k8s/common/mysql#host>
  DB_PASS: <path:kv/data/k8s/common/mysql#password>
  DB_USER: <path:kv/data/k8s/common/mysql#user>
  GMAPS_API_KEY: <gmapsKey>
type: Opaque
